### ISSUE TITLE
sticker file haven't create file

### ISSUE THREAD

**Issue by james111731** [imagitama/vrc-avatar-sticker-generator#1]
hi! 
so I have a problem with the sticker generator. where is done?
then look like don't have a sticker file has created. but not there?
please fix this?
also, sorry  I use Grammarly

**Comment by imagitama** [comment]
Hi - when you use the tool it should output PNG files into a directory called Stickers in the root of your project.

**Comment by imagitama** [comment]
Closed as you haven't replied. The stickers get outputted to a directory called "stickers". I have tested this and it works for me:

![image](https://user-images.githubusercontent.com/1967342/167057664-5fd175fc-ef89-4bba-9b80-f1461797db24.png)
