### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by sheisjustine** [imagitama/vrc-avatar-sticker-generator#2]
I have not been able to get this to work at all, I am clueless.

**Comment by imagitama** [comment]
Have you followed all of the steps? Which step has failed?

**Comment by imagitama** [comment]
Closing as I haven't received a reply. Please make sure you follow the steps in the README and use the latest version, correct Unity version and VRCSDK version.

Steps:

1. Drop this folder into your Assets in your Unity project.
2. Go to PeanutTools -> VRC Avatar Sticker Generator.
3. Fill out the form.
4. Click "Create Stickers". Unity will go into Play Mode and will output to a Stickers folder (root of project).
