### ISSUE TITLE
Generator not appearing

### ISSUE THREAD

**Issue by ArchOwlen** [imagitama/vrc-avatar-sticker-generator#3]
Menu item for the generator is failing to appear

Console error:
Assets\PeanutTools\VRC_Avatar_Sticker_Generator\DebugVRCAvatarStickerGenerator.cs(12,7): error CS0246: The type or namespace name 'cakeslice' could not be found (are you missing a using directive or an assembly reference?)

Version 0.0.6

Relaunching the project makes the VRC SDK fail to load

**Comment by imagitama** [comment]
I'm no longer using cakeslice (instead using ImageMagick). Can you please try deleting the folder and re-importing?

**Comment by imagitama** [comment]
Thanks for the bug report. Fixed in 0.0.7
