### ISSUE TITLE
Camera ignoring offsets, always moving right ontop of the head

### ISSUE THREAD

**Issue by ReikoAldrakar** [imagitama/vrc-avatar-sticker-generator#4]
Camera ignoring offsets, always moving right ontop of the head.
-> The actually recorded area is behind the head
![image](https://user-images.githubusercontent.com/40246719/169742663-24235ef3-708e-4092-992d-a07bbee5e3dc.png)

**Comment by imagitama** [comment]
Thanks for raising the issue. If I ever work on this project again I'll investigate it. I welcome a PR to fix it

**Comment by imagitama** [comment]
The camera now does not zoom in or out. All it does is shift up or down (togglable).
