### ISSUE TITLE
Avatar disappears when in preview mode or sticker creation mode

### ISSUE THREAD

**Issue by StrawdeeryHoobs** [imagitama/vrc-avatar-sticker-generator#5]
When attempting to create the stickers, I am able to choose the avatar that contains the VRChat avatar descriptor and select the Head bone. When I preview, the avatar disappears. When I create stickers, they end up empty. The only items in the Unity project are the avatar (stripped down to standard shaders, in case that has an effect) and the sticker generator files. Nothing else is present. I have tried using this with the VRCSDK, no change, and I have tried using the other shaders bundled with the avatar, still no change.

**Comment by imagitama** [comment]
Thanks for the bug report. I will fix it the next time I work on the project. I welcome any PRs

**Comment by imagitama** [comment]
The tool has been completely rewritten. There is now no longer a preview mode.
